### ISSUE TITLE
sbt assembly fails

### ISSUE THREAD

**Issue by ke4roh** [rnowling/article-deduplication#1]
I'm trying to run this now for the first time:

```
$ sbt assembly
[info] Loading project definition from /home/jscarbor/sources/article-deduplication/project
/home/jscarbor/sources/article-deduplication/build.sbt:33: error: not found: value assemblyMergeStrategy
assemblyMergeStrategy in assembly := {
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

[This answer](http://stackoverflow.com/questions/27198216/sbt-assembly-deduplicate-error-exclude-error) might point in the right direction, but I'm sufficiently new to sbt to not know how to consume the information.

**Comment by rnowling** [comment]
I have a mistake in the build instructions. Can you try

`$ ./sbt assembly`

**Comment by rnowling** [comment]
You could have a different version of sbt on your system. The included script should pull a local copy of the correct version.  If that doesn't fix it, I can try to dig deeper. Currently flying over the atlantic ocean...
